from typing import Final

from trackmod.core.samples.depth import BitDepth
from trackmod.spec.pitch import NOTES_PER_OCTAVE, RATE_NOTE
from trackmod.spec.width import BYTE_MAX, DOUBLE_WORD_MAX, WORD_MAX
from trackmod.xm.spec.sizes import KEYMAP_NOTES
from trackmod.xm.spec.tuning import MAX_RELATIVE_NOTE, MIN_RELATIVE_NOTE, REFERENCE_NOTE, REFERENCE_RATE

PAN_CENTER: Final = 128

MAX_NOTE: Final = KEYMAP_NOTES - 1

MAX_PATTERNS: Final = 256
MAX_ORDERS: Final = 256

MIN_ROWS: Final = 1
MAX_ROWS: Final = 256

CANONICAL_MAX_CHANNELS: Final = 32
EXTENDED_MAX_CHANNELS: Final = BYTE_MAX

CANONICAL_MAX_INSTRUMENTS: Final = 128
EXTENDED_MAX_INSTRUMENTS: Final = BYTE_MAX

CANONICAL_SAMPLES_PER_INSTRUMENT: Final = 16
EXTENDED_SAMPLES_PER_INSTRUMENT: Final = BYTE_MAX
MAX_SAMPLES: Final = CANONICAL_MAX_INSTRUMENTS * CANONICAL_SAMPLES_PER_INSTRUMENT

MIN_SPEED: Final = 1
CANONICAL_MAX_SPEED: Final = 31
MAX_SPEED: Final = WORD_MAX

MIN_TEMPO: Final = 1
CANONICAL_MIN_TEMPO: Final = 32
CANONICAL_MAX_TEMPO: Final = BYTE_MAX
MAX_TEMPO: Final = WORD_MAX

MAX_BREAK_ROW: Final = 99

MAX_SAMPLE_FRAMES: Final = DOUBLE_WORD_MAX // BitDepth.SIXTEEN.bytes_per_frame
MIN_SAMPLE_RATE: Final = round(
    REFERENCE_RATE * 2 ** ((RATE_NOTE + MIN_RELATIVE_NOTE - REFERENCE_NOTE) / NOTES_PER_OCTAVE)
)
MAX_SAMPLE_RATE: Final = round(
    REFERENCE_RATE * 2 ** ((RATE_NOTE + MAX_RELATIVE_NOTE - REFERENCE_NOTE) / NOTES_PER_OCTAVE)
)
