from typing import Final

FILE_HEADER_BYTES: Final = 80
HEADER_SIZE_OFFSET: Final = 60
HEADER_SIZE_FIELD: Final = 276

ORDER_TABLE_BYTES: Final = 256

PATTERN_HEADER_BYTES: Final = 9
INSTRUMENT_HEADER_BYTES: Final = 263
EMPTY_INSTRUMENT_HEADER_BYTES: Final = 29
SAMPLE_HEADER_BYTES: Final = 40

MODULE_NAME_BYTES: Final = 20
TRACKER_NAME_BYTES: Final = 20
NAME_BYTES: Final = 22

KEYMAP_NOTES: Final = 96

ENVELOPE_POINTS: Final = 12
VOLUME_POINTS_OFFSET: Final = 129
PANNING_POINTS_OFFSET: Final = 177
VOLUME_COUNT_OFFSET: Final = 225
PANNING_COUNT_OFFSET: Final = 226
VOLUME_SPAN_OFFSET: Final = 227
PANNING_SPAN_OFFSET: Final = 230
VOLUME_FLAGS_OFFSET: Final = 233
PANNING_FLAGS_OFFSET: Final = 234
