from typing import Final

FILE_HEADER_BYTES: Final = 192
SAMPLE_HEADER_BYTES: Final = 80
INSTRUMENT_HEADER_BYTES: Final = 554
PATTERN_HEADER_BYTES: Final = 8

OFFSET_TABLE_ENTRY_BYTES: Final = 4
OFFSET_CODE: Final = "<I"

NAME_BYTES: Final = 26
FILENAME_BYTES: Final = 12

CHANNELS_STORED: Final = 64

ENVELOPE_NODES: Final = 25
VOLUME_ENVELOPE_OFFSET: Final = 0x130
PANNING_ENVELOPE_OFFSET: Final = 0x182
PITCH_ENVELOPE_OFFSET: Final = 0x1D4
